import React from 'react';
import './about.css';

function About() {
  return (
    <div className="about-container">
      <h1>About Us</h1>
      <div className="faq">
        <h2>Frequently Asked Questions</h2>
        <ul>
          <li><span>Is commercial use allowed?</span> Yes, commercial use is permitted for the generated images. You may utilize these images for any legal purposes. For full details, please refer to our Terms of Service.</li>
          <li><span>Can I use the generated images for NFTs?</span> Yes, they can be used for NFTs.</li>
          <li><span>Is there an API available?</span> Yes! To access all available APIs, please check our documentation here.</li>
          <li><span>Who owns the output?</span> The generated images are considered public domain and hence, they have no owner.</li>
          <li><span>Is there a copyright on the output?</span> The images generated by the AI are not subject to copyright.</li>
          <li><span>Can I get higher resolution or higher quality images?</span> Currently, we do not offer images in higher resolutions or qualities. The available quality will improve over time.</li>
          <li><span>Is the quality of the images suitable for printing?</span> The quality is generally sufficient for printing smaller images. However, larger prints might appear blurry.</li>
        </ul>
      </div>

    </div>
  );
}

export default About;
